### ISSUE TITLE
How do you build the fernflower.jar?

### ISSUE THREAD

**Issue by justechn** [MinecraftForge/FernFlower#1]
You mention using the fernflower.jar, but I cannot seem to find it in this repo. I assume I have to build it, but again there are no instructions on how to do that. I am not a java developer so it would be great if you could provide some steps on how to setup a proper build, or provide a jar file to run. thanks

**Comment by LexManos** [comment]
This main line is auto-built useing a small build.gradle, found we made [here](https://gist.github.com/LexManos/abf02179db7b5b367ee33639e266b34b). And has an auto generated [downloads page](http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/).
The idea is to have the build number be the commit number on the master repo. However that hasn't worked out as there are sometimes multiple commits done between the time our sub-tree split cron job runs. I may go through and change it to be the commit hash. 

Everything in this repo is untouched by anyone. It is purely a sub-tree split of JetBrain's repo. Our intention is to use this repo and apply the [changes](https://github.com/MinecraftForge/FernFlowerLegacy/commits/master) we've been using for quite a while now on to a new cleaner repo [HERE](https://github.com/MinecraftForge/ForgeFlower)

**Comment by kb-1000** [comment]
@LexManos but how do you do that sub-tree split?

**Comment by LexManos** [comment]
https://lostechies.com/johnteague/2014/04/04/using-git-subtrees-to-split-a-repository/
