### ISSUE TITLE
running bug

### ISSUE THREAD

**Issue by A-AFTAHI** [MinecraftForge/FernFlower#2]
hi, thanks for your great effort here.I wanna report that when i run the .jar file with any of the given options all it does is copy the input file to the destination directory without making any changes or generating any resultls. i downloaded the jar file from http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/ . can anyone guide me please to to solv this issue

**Comment by LexManos** [comment]
This is on the wrong repo, this is purely a fork of IntelliJ's repo. Untouched in any way.
So any issues directly with this one should be reported to them.
Our modified version is in the ForgeFlower repo.
